// Extract WordPress i18n strings from the block-editor JS/JSX sources into a POT
// fragment. WP-CLI's `make-pot` JS parser is unavailable in this environment, so
// we walk the Babel AST ourselves (the same approach as @wordpress/babel-plugin-makepot).
// Output is merged with the working PHP scan via `wp i18n make-pot ... --merge`.
import { parse } from '@babel/parser';
import _traverse from '@babel/traverse';
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';

const traverse = _traverse.default || _traverse;
const DOMAIN = 'wp-ai-translate';
const OUT = process.argv[2] || '/tmp/wpait-js.pot';

// Auto-discover every JS source under src/ (excluding test files) so a new entry
// app (e.g. src/overview/) is picked up without editing this list. Refs are the
// plugin-relative path, sorted for deterministic output.
function discover( dir ) {
  const out = [];
  for ( const ent of readdirSync( dir, { withFileTypes: true } ) ) {
    const p = join( dir, ent.name );
    if ( ent.isDirectory() ) {
      out.push( ...discover( p ) );
    } else if ( ent.name.endsWith( '.js' ) && ! ent.name.endsWith( '.test.js' ) ) {
      out.push( [ p, p ] );
    }
  }
  return out;
}
const FILES = discover( 'src' ).sort( ( a, b ) => a[ 0 ].localeCompare( b[ 0 ] ) );

// fn name -> arg positions {single, plural, context, domain}
const FNS = {
  __: { single: 0, domain: 1 },
  _e: { single: 0, domain: 1 },
  esc_html__: { single: 0, domain: 1 },
  esc_attr__: { single: 0, domain: 1 },
  esc_html_e: { single: 0, domain: 1 },
  esc_attr_e: { single: 0, domain: 1 },
  _x: { single: 0, context: 1, domain: 2 },
  esc_html_x: { single: 0, context: 1, domain: 2 },
  _n: { single: 0, plural: 1, domain: 3 },
  _nx: { single: 0, plural: 1, context: 2, domain: 4 },
};

const entries = new Map(); // key: ctxmsgid -> { msgid, plural, ctx, refs:Set, comments:Set, jsFormat }

const lit = (node) =>
  node && node.type === 'StringLiteral' ? node.value : null;

function translatorsComment(path) {
  // Find the nearest leading comment containing "translators:" on an ancestor.
  let p = path;
  while (p) {
    const cs = p.node.leadingComments;
    if (cs) {
      for (const c of cs) {
        const txt = c.value.trim();
        if (/translators:/i.test(txt)) return txt.replace(/\s+/g, ' ');
      }
    }
    p = p.parentPath;
  }
  return null;
}

for (const [file, ref] of FILES) {
  const code = readFileSync(file, 'utf8');
  const ast = parse(code, {
    sourceType: 'module',
    plugins: ['jsx', 'classProperties', 'objectRestSpread', 'optionalChaining', 'nullishCoalescingOperator', 'dynamicImport'],
  });
  traverse(ast, {
    CallExpression(path) {
      const callee = path.node.callee;
      const name = callee.type === 'Identifier' ? callee.name : null;
      if (!name || !FNS[name]) return;
      const spec = FNS[name];
      const args = path.node.arguments;
      const domain = lit(args[spec.domain]);
      if (domain !== DOMAIN) return; // only our domain
      const msgid = lit(args[spec.single]);
      if (msgid === null) return;
      const ctx = spec.context !== undefined ? lit(args[spec.context]) : null;
      const plural = spec.plural !== undefined ? lit(args[spec.plural]) : null;
      const key = (ctx || '') + '' + msgid + '' + (plural || '');
      if (!entries.has(key)) {
        entries.set(key, { msgid, plural, ctx, refs: new Set(), comments: new Set(), jsFormat: false });
      }
      const e = entries.get(key);
      e.refs.add(`${ref}:${path.node.loc.start.line}`);
      const tc = translatorsComment(path);
      if (tc) e.comments.add(tc);
      if (/%[0-9]*[sd$]/.test(msgid) || (plural && /%[0-9]*[sd$]/.test(plural))) e.jsFormat = true;
    },
  });
}

const esc = (s) =>
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t');

let out = '# JS i18n fragment (generated by extract-js-i18n.mjs).\nmsgid ""\nmsgstr ""\n"Content-Type: text/plain; charset=UTF-8\\n"\n\n';
for (const e of entries.values()) {
  for (const c of e.comments) out += `#. ${c}\n`;
  for (const r of [...e.refs].sort()) out += `#: ${r}\n`;
  if (e.jsFormat) out += '#, js-format\n';
  if (e.ctx) out += `msgctxt "${esc(e.ctx)}"\n`;
  out += `msgid "${esc(e.msgid)}"\n`;
  if (e.plural) {
    out += `msgid_plural "${esc(e.plural)}"\n`;
    out += 'msgstr[0] ""\nmsgstr[1] ""\n\n';
  } else {
    out += 'msgstr ""\n\n';
  }
}
writeFileSync(OUT, out);
console.log(`extracted ${entries.size} JS strings -> ${OUT}`);

// Fail loud on a zero/regressed extraction. A broken parser (e.g. the transitive
// @babel/parser dep getting deduped away) silently emits 0 strings, which is how
// the .pot previously rotted. Exit non-zero so `npm run make-pot`/CI catches it.
// WPAIT_I18N_MIN_STRINGS sets a stricter floor than the default of 1.
const MIN = Number.parseInt(process.env.WPAIT_I18N_MIN_STRINGS || '1', 10);
if (entries.size < MIN) {
  console.error(
    `ERROR: extracted ${entries.size} JS i18n strings, expected at least ${MIN}. ` +
    `The extractor likely failed to parse src/ (missing @babel/parser/@babel/traverse, ` +
    `or a source/glob change). Refusing to emit a regressed .pot.`
  );
  process.exit(1);
}
