<?php
/**
 * Harness seed: example posts, categories, and tags in US English (en_US) and
 * Argentinean Spanish (es_AR), with translation groups wired up so the plugin's
 * front-end blocks and admin lists have realistic data to render.
 *
 * Run via the harness:  playground.sh wp -- eval-file harness/seed-content.php
 * (or ./harness/up.sh, which calls this). Safe to re-run with --force.
 *
 * This is a TEST HARNESS seed, not a demo of AI translation: the es_AR posts are
 * authored directly (not generated by the connector) and linked to their en
 * siblings by hand, because Playground has no AI provider configured
 * (wp_supports_ai() is false). That keeps the harness self-contained.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Should only run via wp eval-file.
}

if ( ! function_exists( 'wpait' ) ) {
	WP_CLI::warning( 'wp-ai-translate plugin is not active — run `playground.sh wp -- plugin activate wp-ai-translate` first.' );
	return;
}

$force = isset( $args ) && is_array( $args ) && in_array( '--force', $args, true );
if ( ! $force && get_option( 'wpait_harness_seeded' ) ) {
	WP_CLI::log( 'Harness already seeded (option wpait_harness_seeded set). Re-run with --force to reseed.' );
	return;
}

$languages = wpait()->languages();
$store     = wpait()->store();
$settings  = Wpait_Admin_Settings::get_settings();

// --- 1. Configure two languages: en (US English) + es (Argentinean Spanish). ---
$lang_rows = array(
	array(
		'code'    => 'en',
		'locale'  => 'en_US',
		'name'    => 'English',
		'native'  => 'English',
		'flag'    => '🇺🇸',
		'enabled' => true,
	),
	array(
		'code'    => 'es',
		'locale'  => 'es_AR',
		'name'    => 'Spanish',
		'native'  => 'Español (Argentina)',
		'flag'    => '🇦🇷',
		'enabled' => true,
	),
);

$reconcile = $languages->reconcile( $lang_rows, $settings['languages'] );

$new_settings = $settings;
$new_settings['languages']        = $reconcile['languages'];
$new_settings['default_language'] = 'en';
// A per-language instruction so the prompt-composition path has something to show.
$new_settings['instructions']['per_language']['es'] =
	'Use Argentinean Spanish (rioplatense). Prefer "vos" forms where natural; keep it friendly and informal.';
update_option( Wpait_Admin_Settings::OPTION, $new_settings );
$languages::flush_index();

// --- 2. Categories and tags, with languages + translation-group links. ---
// Helper: create or find a term by slug, set its language, return term id.
$ensure_term = static function ( $taxonomy, $name, $slug, $code ) use ( $store ) {
	$term = get_term_by( 'slug', $slug, $taxonomy );
	if ( ! $term ) {
		$res = wp_insert_term( $name, $taxonomy, array( 'slug' => $slug ) );
		if ( is_wp_error( $res ) ) {
			WP_CLI::warning( "term create failed ($taxonomy/$slug): " . $res->get_error_message() );
			return 0;
		}
		$term_id = (int) $res['term_id'];
	} else {
		$term_id = (int) $term->term_id;
		wp_update_term( $term_id, $taxonomy, array( 'name' => $name ) );
	}
	$store->set_language( 'term', $term_id, $code );
	return $term_id;
};

$cat_gardening_en = $ensure_term( 'category', 'Gardening', 'gardening', 'en' );
$cat_gardening_es = $ensure_term( 'category', 'Jardinería', 'jardineria', 'es' );
if ( $cat_gardening_en && $cat_gardening_es ) {
	$store->link_translation( 'term', $cat_gardening_en, $cat_gardening_es );
}

$cat_travel_en = $ensure_term( 'category', 'Travel', 'travel', 'en' );
$cat_travel_es = $ensure_term( 'category', 'Viajes', 'viajes', 'es' );
if ( $cat_travel_en && $cat_travel_es ) {
	$store->link_translation( 'term', $cat_travel_en, $cat_travel_es );
}

$cat_guides_en = $ensure_term( 'category', 'Guides', 'guides', 'en' );
$cat_guides_es = $ensure_term( 'category', 'Guías', 'guias', 'es' );
if ( $cat_guides_en && $cat_guides_es ) {
	$store->link_translation( 'term', $cat_guides_en, $cat_guides_es );
}

$tag_coffee_en = $ensure_term( 'post_tag', 'coffee', 'coffee', 'en' );
$tag_cafe_es   = $ensure_term( 'post_tag', 'café', 'cafe', 'es' );
if ( $tag_coffee_en && $tag_cafe_es ) {
	$store->link_translation( 'term', $tag_coffee_en, $tag_cafe_es );
}

$tag_brewing_en = $ensure_term( 'post_tag', 'brewing', 'brewing', 'en' );
$tag_mate_es    = $ensure_term( 'post_tag', 'mate', 'mate', 'es' );
$tag_argentina  = $ensure_term( 'post_tag', 'argentina', 'argentina', 'es' );
$tag_travel_en  = $ensure_term( 'post_tag', 'travel', 'travel', 'en' );
$tag_viajes_es  = $ensure_term( 'post_tag', 'viajes', 'viajes-es', 'es' );

// --- 3. Posts in both languages, with block markup; link en/es pairs as groups. ---
// Helper: create or update a post by slug, set language + terms, return id.
$ensure_post = static function ( $args ) use ( $store ) {
	$args = wp_parse_args(
		$args,
		array( 'post_status' => 'publish', 'post_type' => 'post' )
	);
	$existing = get_page_by_path( $args['post_name'], OBJECT, $args['post_type'] );
	if ( $existing ) {
		$args['ID'] = $existing->ID;
	}
	$id = wp_insert_post( wp_slash( $args ), true );
	if ( is_wp_error( $id ) ) {
		WP_CLI::warning( "post create failed ({$args['post_name']}): " . $id->get_error_message() );
		return 0;
	}
	$id = (int) $id;
	$store->set_language( 'post', $id, $args['lang'] );
	if ( ! empty( $args['cats'] ) ) {
		wp_set_post_categories( $id, $args['cats'] );
	}
	if ( ! empty( $args['tags'] ) ) {
		wp_set_post_tags( $id, $args['tags'], false );
	}
	return $id;
};

// A couple of shared block snippets. The post-links block is appended to linked
// posts so the front-end demonstrates the sibling-links block out of the box.
$links_block = '<!-- wp:wp-ai-translate/post-links /-->';

$en_garden = $ensure_post( array(
	'post_name'    => 'the-blue-garden',
	'post_title'   => 'The Blue Garden',
	'post_excerpt' => 'A quiet corner of the city built around blue flowers and silver foliage.',
	'post_content' => '<!-- wp:paragraph --><p>Three summers ago I tore out a tired lawn and planted a garden in shades of blue. The neighbors were skeptical, but by July the agapanthus and salvia were humming with bees.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Why blue?</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Blue recedes, so a small plot feels deeper than it is. Pair it with silvers and grays and the whole space reads cool even on a ninety-degree day.</p><!-- /wp:paragraph -->
<!-- wp:list --><ul><li>Agapanthus for height</li><li>Salvia for the bees</li><li>Silver Artemisia to frame it</li></ul><!-- /wp:list -->',
	'lang'        => 'en',
	'cats'        => array( $cat_gardening_en ),
	'tags'        => array( $tag_travel_en ),
) );

$es_garden = $ensure_post( array(
	'post_name'    => 'el-jardin-azul',
	'post_title'   => 'El jardín azul',
	'post_excerpt' => 'Un rincón tranquilo de la ciudad armado con flores azules y follaje plateado.',
	'post_content' => '<!-- wp:paragraph --><p>Hace tres veranos saqué un pasto cansado y planté un jardín en tonos azules. Los vecinos desconfiaban, pero para julio los agapandos y las salvias zumbaban de abejas.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">¿Por qué azul?</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>El azul se aleja, así que un patio chico parece más grande de lo que es. Combinado con plateados y grises, todo el espacio se siente fresco incluso a la siesta, con treinta grados.</p><!-- /wp:paragraph -->
<!-- wp:list --><ul><li>Agapandos para dar altura</li><li>Salvia para las abejas</li><li>Artemisia plateada para enmarcar</li></ul><!-- /wp:list -->',
	'lang'        => 'es',
	'cats'        => array( $cat_gardening_es ),
	'tags'        => array( $tag_viajes_es ),
) );

$en_coffee = $ensure_post( array(
	'post_name'    => 'pour-over-coffee-basics',
	'post_title'   => 'Pour-Over Coffee Basics',
	'post_excerpt' => 'A repeatable method for a clean, bright cup at home.',
	'post_content' => '<!-- wp:paragraph --><p>Pour-over is the most forgiving way to make a single cup. Grind medium, wet the grounds, wait thirty seconds, then pour in slow circles.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">The recipe</h2><!-- /wp:heading -->
<!-- wp:list --><ol><li>22g coffee, 360g water</li><li>Bloom for 30s</li><li>Pour to 200g by 1:15</li><li>Finish at 360g by 2:30</li></ol><!-- /wp:list -->
<!-- wp:paragraph --><p>If it tastes sour, grind finer; if bitter, grind coarser. That is the whole game.</p><!-- /wp:paragraph -->',
	'lang'        => 'en',
	'cats'        => array( $cat_guides_en ),
	'tags'        => array( $tag_coffee_en, $tag_brewing_en ),
) );

$es_mate = $ensure_post( array(
	'post_name'    => 'como-preparar-mate',
	'post_title'   => 'Cómo preparar mate',
	'post_excerpt' => 'La guía para cebar un mate rico, sin lavarlo y sin que se lave.',
	'post_content' => '<!-- wp:paragraph --><p>Cebar mate es un ritual más que una receta. La clave es el agua caliente, nunca hirviendo, y respetar la montañita de yerba.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Paso a paso</h2><!-- /wp:heading -->
<!-- wp:list --><ol><li>Llená el mate tres cuartos con yerba</li><li>Formá la montañita de un lado</li><li>Verté agua tibia sobre la yerba fría y esperá un minuto</li><li>Insertá la bomba del lado vacío</li><li>Cebá con agua a punto, sin revolver</li></ol><!-- /wp:list -->
<!-- wp:paragraph --><p>Si el mate se lava rápido, probablemente el agua estaba demasiado caliente. Probá con unos grados menos.</p><!-- /wp:paragraph -->',
	'lang'        => 'es',
	'cats'        => array( $cat_guides_es ),
	'tags'        => array( $tag_mate_es, $tag_argentina ),
) );

$en_brooklyn = $ensure_post( array(
	'post_name'    => 'weekend-in-brooklyn',
	'post_title'   => 'A Weekend in Brooklyn',
	'post_excerpt' => 'Two days of bagels, bookshops, and walking the bridge.',
	'post_content' => '<!-- wp:paragraph --><p>Brooklyn rewards walkers. Start in DUMBO, cross the bridge on foot, and end the day with a book in Prospect Park.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Saturday</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Bagel at 9, the Brooklyn Bridge by 10, and a long afternoon in the museum.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Sunday</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Coffee, bookshops, and the park. Do not overplan it.</p><!-- /wp:paragraph -->',
	'lang'        => 'en',
	'cats'        => array( $cat_travel_en ),
	'tags'        => array( $tag_travel_en ),
) );

$es_buenos_aires = $ensure_post( array(
	'post_name'    => 'fin-de-semana-en-buenos-aires',
	'post_title'   => 'Fin de semana en Buenos Aires',
	'post_excerpt' => 'Dos días de café, librerías y caminatas por San Telmo y Palermo.',
	'post_content' => '<!-- wp:paragraph --><p>Buenos Aires se camina. Arrancá en San Telmo, subí hasta Palermo y terminá el día con un café en una esquina con mesas en la vereda.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Sábado</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Fería de San Telmo a la mañana, asado a la siesta y una vuelta por Puerto Madero al caer la tarde.</p><!-- /wp:paragraph -->
<!-- wp:heading --><h2 class="wp-block-heading">Domingo</h2><!-- /wp:heading -->
<!-- wp:paragraph --><p>Mate en la plaza, librerías de Palermo y un paseo por los bosques. No planiues demasiado.</p><!-- /wp:paragraph -->',
	'lang'        => 'es',
	'cats'        => array( $cat_travel_es ),
	'tags'        => array( $tag_viajes_es, $tag_argentina ),
) );

// Link the two en/es pairs that are translations of each other.
foreach ( array( array( $en_garden, $es_garden ), array( $en_brooklyn, $es_buenos_aires ) ) as $pair ) {
	if ( $pair[0] && $pair[1] ) {
		$store->link_translation( 'post', $pair[0], $pair[1] );
	}
}

// Append the post-links block to the linked posts so the front-end shows siblings.
foreach ( array( $en_garden, $es_garden, $en_brooklyn, $es_buenos_aires ) as $pid ) {
	if ( ! $pid ) {
		continue;
	}
	$post = get_post( $pid );
	if ( ! $post ) {
		continue;
	}
	if ( false === strpos( $post->post_content, 'wp:wp-ai-translate/post-links' ) ) {
		wp_update_post( array( 'ID' => $pid, 'post_content' => $post->post_content . "\n\n" . $links_block ) );
	}
}

// --- 4. Tidy the default WP content so the seeded list is the front page. ---
$hello = get_page_by_path( 'hello-world', OBJECT, 'post' );
if ( $hello ) {
	wp_delete_post( $hello->ID, true );
}
$first_comment = get_comments( array( 'number' => 1, 'fields' => 'ids' ) );
foreach ( $first_comment as $cid ) {
	wp_delete_comment( $cid, true );
}

update_option( 'wpait_harness_seeded', time() );

// --- 5. Summary an agent can read. ---
$report = array(
	'languages' => wp_list_pluck( $reconcile['languages'], 'code' ),
	'reconcile' => $reconcile['report'],
	'posts'     => array(),
	'terms'     => array(),
);
foreach ( array( $en_garden, $es_garden, $en_coffee, $es_mate, $en_brooklyn, $es_buenos_aires ) as $pid ) {
	if ( ! $pid ) {
		continue;
	}
	$report['posts'][] = array(
		'ID'    => $pid,
		'title' => get_the_title( $pid ),
		'lang'  => $store->get_language( 'post', $pid ),
		'group' => $store->get_group( 'post', $pid ),
		'url'   => get_permalink( $pid ),
	);
}
foreach ( array( $cat_gardening_en, $cat_gardening_es, $cat_travel_en, $cat_travel_es, $cat_guides_en, $cat_guides_es ) as $tid ) {
	if ( ! $tid ) {
		continue;
	}
	$t = get_term( $tid );
	$report['terms'][] = array( 'ID' => $tid, 'name' => $t->name, 'lang' => $store->get_language( 'term', $tid ), 'group' => $store->get_group( 'term', $tid ) );
}
WP_CLI::success( 'Harness seeded: ' . json_encode( $report ) );
